Repository openware/barong, pull requests merged in 2018-10, with the labels that each got.

#630 Fix issue with jwt in dev mode
  config/secrets.yml
Labels: PR: approved

#633 Fix bootstrap vulnerability by upgrading gem to 4.1.2 version
  Gemfile
  Gemfile.lock
Labels: PR: approved

#639 Add grape logger middleware
  Gemfile
  Gemfile.lock
  app/api/management_api/v1/base.rb
  app/api/user_api/v1/base.rb
Labels: PR: approved, v1.8

#624 Add grape logger middleware
  Gemfile
  Gemfile.lock
  app/api/management_api/v1/base.rb
  app/api/user_api/v1/base.rb
Labels: PR: approved, v1.9
