Repository openware/barong, pull requests merged in 2018-03, with the labels that each got.

#194 Fixed bin/setup to work in correct order
  bin/setup
  config/seed.yml
  db/seeds.rb
Labels: approved

#215 Add chrome in .travis.yml & update chromedriver-helper (closes #213)
  .travis.yml
  Gemfile.lock
Labels: approved

#222 Fix phones notification color
  app/controllers/phones_controller.rb
Labels: approved

#233 Final issue in travis configuration
  .travis.yml
Labels: approved

#257 Use email as account name in Vault TOTP; allow setting issuer name in env
  app/controllers/security_controller.rb
  lib/vault/totp.rb
Labels: PR: approved

#249 #247 Add focus to email input at page load and password input
  app/views/devise/sessions/confirm.html.erb
Labels: PR: approved

#259 Fix multiple issue with cloud storage configurations
  config/charts/barong/templates/_helpers.tpl
  config/charts/barong/templates/secrets.yaml
  config/charts/barong/values.yaml
  config/initializers/carrierwave.rb
Labels: PR: approved

#256 Update travis CI script as rubykube/peatio#639 (closes #255)
  ci/bump.rb
Labels: PR: approved

#270 Set account state along with profile state
  app/controllers/admin/profiles_controller.rb
Labels: double check

#271 Added get profile API call
  app/controllers/api/v1/base.rb
  app/controllers/api/v1/profiles.rb
Labels: PR: approved

#273 Added state for GET profile
  app/controllers/api/v1/profiles.rb
Labels: PR: approved

#279 Set account state to 'active' on email confirmation
  app/controllers/admin/profiles_controller.rb
  app/models/account.rb
Labels: PR: approved

#287 Updated loofah to 2.2.2
  Gemfile.lock
Labels: PR: approved

#290 Updated loofah to 2.2.2
  Gemfile.lock
Labels: PR: approved

#264 Implemented API JWT renewal
  app/controllers/api/v1/base.rb
  app/controllers/api/v1/security.rb
  config/initializers/doorkeeper.rb
  docs/api.md
  lib/barong/security/access_token.rb
  spec/api/security_spec.rb
  spec/factories/doorkeeper_application.rb
  spec/factories/doorkeeper_token.rb
Labels: PR: approved

#302 Ignore yarn files
  .gitignore
Labels: PR: approved
