Repository openware/barong, pull requests merged in 2018-12, with the labels that each got.

#671 Hotfix for rack_attack
  config/initializers/rack_attack.rb
Labels: PR: approved

#672 Make documents invisible publicly by changing fog policy
  app/uploaders/upload_uploader.rb
Labels: PR: approved, type: fix, v2

#674 Added missing validations on password update functionality
  app/api/v2/identity/users.rb
  app/models/user.rb
  spec/api/v2/identity/users_spec.rb
Labels: PR: approved, type: fix, v2

#673 Make documents invisible publicly by changing fog policy
  app/uploaders/upload_uploader.rb
Labels: PR: approved, type: fix, v1.9

#650 Unlock account after 1 hour of being locked
  app/api/user_api/v1/sessions.rb
  config/initializers/devise.rb
Labels: PR: approved, type: fix, v1.8

#678 Add codeclimate config file
  .codeclimate.yml
Labels: PR: approved

#675 Fix unhandled totp errors
  app/api/v2/management/base.rb
  app/api/v2/resource/api_keys.rb
  app/api/v2/resource/base.rb
Labels: PR: approved, type: fix, v2

#677 Improve activities coverage
  .codeclimate.yml
  app/api/v2/identity/sessions.rb
  app/api/v2/identity/users.rb
  app/api/v2/identity/utils.rb
  app/api/v2/resource/otp.rb
  app/api/v2/resource/users.rb
  app/api/v2/resource/utils.rb
  app/models/concerns/trusty_agent_validator.rb
  spec/factories/activity.rb
  spec/models/activity_spec.rb
Labels: PR: approved

#679 Add ability to upload multiple documents
  app/api/v2/resource/documents.rb
  spec/api/v2/resource/documents_spec.rb
Labels: PR: approved

#669 Add base swagger configuration and documentation for API
  .codeclimate.yml
  app/api/v2/base.rb
  app/api/v2/entities/api_key.rb
  app/api/v2/identity/base.rb
  app/api/v2/management/base.rb
  app/api/v2/management/jwt_authentication_middleware.rb
  app/api/v2/resource/base.rb
  docs/barong_api_v2.md
  docs/swagger.json
  lib/barong/middleware/jwt_authenticator.rb
Labels: PR: approved

#685 Update the production database configuration with DATABASE_NAME from env
  config/database.yml
Labels: PR: approved

#688 Add change password endpoint
  app/api/v2/resource/otp.rb
  app/api/v2/resource/users.rb
  app/api/v2/resource/utils.rb
  spec/api/v2/resource/users_spec.rb
Labels: PR: approved

#665 GeeTest.com captcha integration on Barong v2
  app/api/v2/identity/sessions.rb
  app/api/v2/identity/users.rb
  app/api/v2/identity/utils.rb
  app/services/captcha_service.rb
  app/services/recaptcha_verifier.rb
  config/initializers/captcha_policy.rb
  config/initializers/geetest.rb
  lib/barong/captcha_policy.rb
  spec/api/v2/identity/sessions_spec.rb
  spec/api/v2/identity/users_spec.rb
Labels: PR: approved

#681 Feature/admin api
  Gemfile
  Gemfile.lock
  app/api/v2/admin/base.rb
  app/api/v2/admin/users.rb
  app/api/v2/base.rb
  app/api/v2/entities/document.rb
  app/api/v2/entities/user_with_full_info.rb
  app/api/v2/resource/documents.rb
  app/api/v2/resource/otp.rb
  app/api/v2/validations.rb
  app/models/document.rb
  app/models/level.rb
  spec/api/v2/admin/users_spec.rb
Labels: PR: approved

#693 Change multiple docs uploading logic from object to array
  app/api/v2/resource/documents.rb
  spec/api/v2/resource/documents_spec.rb
Labels: PR: approved, Priority: high

#694 Added missing event with confirmation token on signup
  .codeclimate.yml
  app/api/v2/identity/users.rb
  app/api/v2/identity/utils.rb
Labels: PR: approved, Priority: high

#695 Update the Drone CI to replace Travis and DockerHub
  .drone.yml
  lib/tasks/release.rake
Labels: PR: do not merge, in progress

#697 Add label on profile adding without level increase
  app/api/v2/resource/profiles.rb
Labels: PR: approved

#696 Admin update label func and resourse api labels CRUD
  .codeclimate.yml
  app/api/v2/admin/users.rb
  app/api/v2/resource/base.rb
  app/api/v2/resource/labels.rb
  spec/api/v2/resource/labels_spec.rb
Labels: PR: approved

#699 Add carrierwave config for production
  config/initializers/carrierwave.rb
Labels: PR: approved

#702 Small fixes (drone ci, event api updated_at bug)
  .drone.yml
  lib/barong/event_api.rb
Labels: PR: approved, type: fix, v2

#700 Add ability to lock account, add filter for state on admin index
  app/controllers/admin/accounts_controller.rb
  app/models/account.rb
  app/views/admin/accounts/edit.html.erb
  app/views/admin/accounts/index.html.erb
  config/locales/devise.en.yml
Labels: PR: approved, type: feature, v1.8

#701 Add ability to lock account, add filter for state on admin index
  app/controllers/admin/accounts_controller.rb
  app/models/account.rb
  app/views/admin/accounts/edit.html.erb
  app/views/admin/accounts/index.html.erb
  config/locales/devise.en.yml
Labels: PR: approved, type: feature, v1.9
