Repository openware/barong, pull requests merged in 2018-09, with the labels that each got.

#607 #PPBB-45: Allow to configure multiple CORS at barong
  app/api/user_api/v1/cors/middleware.rb
  config/initializers/cors.rb
  spec/api/user_api/v1/cors_spec.rb
Labels: PR: approved, v1.9

#609 Fix message error
  app/views/security/enable.html.erb
Labels: PR: approved, v1.8

#601 Fix message error
  app/views/security/enable.html.erb
Labels: PR: approved

#596 barong fixing security flags in docs
  app/api/user_api/v1/accounts.rb
  app/api/user_api/v1/api_keys.rb
  app/api/user_api/v1/base.rb
  app/api/user_api/v1/documents.rb
  app/api/user_api/v1/labels.rb
  app/api/user_api/v1/phones.rb
  app/api/user_api/v1/profiles.rb
  app/api/user_api/v1/security.rb
Labels: PR: approved, v1.9

#600 Dont let not active accounts to sign in
  app/models/account.rb
  db/schema.rb
  spec/api/user_api/v1/sessions_spec.rb
Labels: PR: approved, v1.8

#612 Add ROOT_DOMAIN for configure sessions
  config/environments/production.rb
Labels: PR: approved, v1.8

#611 Add ROOT_DOMAIN for configure sessions
  config/environments/production.rb
Labels: PR: approved, v1.9

#592 Update api_keys.md
  docs/api/api_keys.md
Labels: PR: approved, v1.9

#608 Dont let not active accounts to sign in
  app/models/account.rb
  db/schema.rb
  spec/api/user_api/v1/sessions_spec.rb
Labels: PR: approved, v1.9

#578 README.md update steps to get project running
  README.md
Labels: PR: approved, v1.9
