Repository openware/barong, pull requests merged in 2018-05, with the labels that each got.

#446 Send emails if they are enabled. Add SKIP_EMAILS env
  app/mailers/account_mailer.rb
  app/mailers/application_mailer.rb
  app/mailers/concerns/skip_emails.rb
  app/mailers/profile_review_mailer.rb
  config/initializers/devise.rb
Labels: PR: approved

#452 Remove outdated deployment stuff
  Makefile
  VERSION
  config/charts/barong/Chart.yaml
  config/charts/barong/templates/NOTES.txt
  config/charts/barong/templates/_helpers.tpl
  config/charts/barong/templates/deployment.yaml
  config/charts/barong/templates/hooks/prepare-db.yaml
  config/charts/barong/templates/ingress.yaml
  config/charts/barong/templates/secrets.yaml
  config/charts/barong/templates/service.yaml
  config/charts/barong/values.yaml
Labels: PR: approved

#448 Add condition for unconfirmed emails check on session#create api endpoint
  app/api/user_api/v1/sessions.rb
  spec/api/user_api/v1/sessions_spec.rb
Labels: PR: approved

#459 Add sentry
  Gemfile
  Gemfile.lock
  config/initializers/sentry.rb
Labels: 1.8 release, PR: approved

#441 Add api_key resource and generate jwt session
  .codeclimate.yml
  app/api/entities/api_key.rb
  app/api/management_api/v1/jwt_authentication_middleware.rb
  app/api/user_api/v1/api_keys.rb
  app/api/user_api/v1/base.rb
  app/api/user_api/v1/security.rb
  app/api/user_api/v1/session_jwt_generator.rb
  app/api/user_api/v1/sessions.rb
  app/models/account.rb
  app/models/api_key.rb
  app/models/level.rb
  app/models/phone.rb
  db/migrate/20180503073934_create_api_keys.rb
  db/schema.rb
  docs/index.md
  docs/specs/api_keys.md
  spec/api/user_api/v1/api_keys_spec.rb
  spec/api/user_api/v1/security_spec.rb
  spec/api/user_api/v1/sessions_spec.rb
  spec/factories/api_keys.rb
  spec/models/api_key_spec.rb
  spec/support/helpers.rb
Labels: v1.8

#461 Bugfix/fix phone validation
  app/assets/javascripts/web.js
  lib/phone_utils.rb
Labels: v1.8

#455 Added password strength validation
  Gemfile
  Gemfile.lock
  app/models/account.rb
  config/initializers/devise-security.rb
  config/locales/devise.security_extension.de.yml
  config/locales/devise.security_extension.en.yml
  config/locales/devise.security_extension.it.yml
  lib/tasks/db_load_fake.rake
  spec/api/user_api/v1/accounts_spec.rb
  spec/api/user_api/v1/security_spec.rb
  spec/api/user_api/v1/sessions_spec.rb
  spec/factories/account.rb
  spec/features/sign_up_spec.rb
  spec/models/account_spec.rb
  spec/views/documents/new.html.erb_spec.rb
Labels: PR: approved

#460 Move all logic from profile show to accounts show. Show Phones and Account info
  app/controllers/admin/accounts_controller.rb
  app/controllers/admin/labels_controller.rb
  app/controllers/admin/profiles_controller.rb
  app/models/account.rb
  app/models/document.rb
  app/models/label.rb
  app/models/profile.rb
  app/views/admin/accounts/_document_label.html.erb
  app/views/admin/accounts/edit.html.erb
  app/views/admin/accounts/index.html.erb
  app/views/admin/accounts/show.html.erb
  app/views/admin/profiles/_form.html.erb
  app/views/admin/profiles/edit.html.erb
  app/views/admin/profiles/index.html.erb
  app/views/admin/profiles/show.html.erb
  app/views/admin/shared/_navigation.html.erb
  app/views/profile_review_mailer/approved.html.erb
  app/views/profile_review_mailer/rejected.html.erb
  config/routes.rb
  db/migrate/20180430172330_remove_state_from_profiles.rb
  db/migrate/20180507162420_add_unique_index_to_labels.rb
  db/schema.rb
  spec/api/user_api/v1/profiles_spec.rb
  spec/controllers/admin/accounts_controller_spec.rb
  spec/controllers/admin/profiles_controller_spec.rb
  spec/factories/profile.rb
  spec/models/document_spec.rb
  spec/models/label_spec.rb
  spec/models/profile_spec.rb
Labels: PR: approved, v1.8

#451 Mark account as discarded istead of delete it
  Gemfile
  Gemfile.lock
  app/api/management_api/v1/labels.rb
  app/api/user_api/v1/helpers.rb
  app/api/user_api/v1/security.rb
  app/api/user_api/v1/sessions.rb
  app/controllers/admin/accounts_controller.rb
  app/controllers/admin/labels_controller.rb
  app/controllers/admin/profiles_controller.rb
  app/controllers/sessions_controller.rb
  app/models/account.rb
  app/models/document.rb
  app/models/label.rb
  app/models/phone.rb
  app/models/profile.rb
  config/initializers/doorkeeper.rb
  db/migrate/20180508095253_add_discarded_at_to_accounts.rb
  db/schema.rb
  db/seeds.rb
  spec/controllers/admin/accounts_controller_spec.rb
  spec/controllers/admin/profiles_controller_spec.rb
Labels: v1.8

#464 Feature: Add metadata to documents API
  app/api/user_api/v1/documents.rb
  app/models/document.rb
  db/migrate/20180507095118_add_metadata_to_documents.rb
  db/schema.rb
  spec/api/user_api/v1/documents_spec.rb
Labels: v1.8

#469 ci/bump pagination patch for 1.7
  ci/bump.rb
Labels: v1.7

#487 Fix typo in phone exists message error
  .travis.yml
  app/api/user_api/v1/helpers.rb
  spec/api/user_api/v1/phones_spec.rb
Labels: v1.8

#498 Feed existing account with labels corresponding their level [for migration from 1.7 to 1.8]
  lib/tasks/add_labels_according_to_level.rake
Labels: PR: approved

#490 Fix document types
  app/models/document.rb
Labels: PR: approved, v1.8

#472 Downcase label key and value before save it
  app/models/label.rb
  spec/models/label_spec.rb
Labels: PR: approved, v1.8

#502 Add new document type
  app/models/document.rb
Labels: PR: approved, v1.8
