Repository openware/barong, pull requests merged in 2018-04, with the labels that each got.

#305 Fix travis-ci version bump
  .travis.yml
  ci/bump.rb
Labels: PR: approved

#312 Add documentation for entities
  app/controllers/api/v1/entities/account.rb
  app/controllers/api/v1/entities/document.rb
  app/controllers/api/v1/entities/profile.rb
Labels: PR: approved

#328 #306: labels api
  Gemfile
  Gemfile.lock
  app/controllers/api/entities/label.rb
  app/controllers/api/v1/base.rb
  app/controllers/api/v1/labels.rb
  app/models/account.rb
  app/models/label.rb
  db/migrate/20180402133658_create_labels.rb
  db/schema.rb
  spec/api/labels_spec.rb
  spec/factories/labels.rb
Labels: PR: approved

#309 Feature/phones api
  app/controllers/api/v1/base.rb
  app/controllers/api/v1/phones.rb
  app/controllers/phones_controller.rb
  app/models/account.rb
  app/models/phone.rb
  db/migrate/20180402145952_add_verification_code.rb
  db/schema.rb
  lib/phone_utils.rb
  spec/api/v1/accounts_spec.rb
  spec/api/v1/phones_spec.rb
  spec/factories/phones.rb
  spec/support/api_helpers.rb
Labels: PR: approved

#352 Start Barong 1.7.0 development!
  lib/barong/version.rb
Labels: PR: approved

#341 Fix phone verification issue
  .codeclimate.yml
  Gemfile
  Gemfile.lock
  app/controllers/phones_controller.rb
  app/models/phone.rb
  lib/phone_utils.rb
  spec/controllers/phones_controller_spec.rb
  spec/spec_helper.rb
  spec/support/devise.rb
Labels: PR: approved

#327 Feature/2fa api
  .codeclimate.yml
  Gemfile
  Gemfile.lock
  app/controllers/api/v1/security.rb
  app/controllers/application_controller.rb
  app/controllers/security_controller.rb
  app/controllers/sessions_controller.rb
  app/models/account.rb
  app/views/layouts/shared/_account_footer.html.erb
  app/views/security/enable.html.erb
  config/routes.rb
  db/migrate/20180404153832_add_otp_enabled_to_accounts.rb
  db/schema.rb
  lib/vault/totp.rb
  spec/api/v1/accounts_spec.rb
  spec/api/v1/security_spec.rb
  spec/features/sign_in_spec.rb
  spec/support/capybara.rb
  spec/support/devise.rb
Labels: PR: approved

#336 Feature/profiles api
  app/controllers/api/v1/profiles.rb
  app/models/profile.rb
  db/migrate/20180410093510_add_metadata_column_to_profiles.rb
  db/schema.rb
  spec/api/v1/profiles_spec.rb
Labels: PR: approved

#357 Fix typo in error rescue
  lib/vault/totp.rb
Labels: PR: approved, type: bug

#360 User level is downgraded to 2 when his profile is rejected
  app/controllers/admin/profiles_controller.rb
Labels: PR: approved, type: bug

#372 Notify user by email when his state changes
  app/controllers/admin/profiles_controller.rb
  app/mailers/profile_review_mailer.rb
  app/models/profile.rb
  app/views/profile_review_mailer/approved.html.erb
  app/views/profile_review_mailer/rejected.html.erb
  spec/factories/profile.rb
  spec/models/profile_spec.rb
Labels: PR: approved, type: enhancement

#374 Notify user by email when his state changes
  app/controllers/admin/profiles_controller.rb
  app/mailers/profile_review_mailer.rb
  app/models/profile.rb
  app/views/profile_review_mailer/approved.html.erb
  app/views/profile_review_mailer/rejected.html.erb
  spec/factories/profile.rb
  spec/models/profile_spec.rb
Labels: PR: approved

#384 Release 1.7.0
  .widdershins.json
  docs/api.md
  docs/index.md
  docs/releases/1.7.0.md
  lib/barong/version.rb
  lib/tasks/slate.rake
Labels: PR: approved

#393 Fix errors in phones api
  .gitignore
  Gemfile
  Gemfile.lock
  app/controllers/api/v1/accounts.rb
  app/controllers/api/v1/base.rb
  app/controllers/api/v1/helpers.rb
  app/controllers/api/v1/phones.rb
  app/models/phone.rb
  config/initializers/fake_twilio.rb
  db/migrate/20180423125629_change_uniq_phones_index.rb
  db/schema.rb
  spec/api/v1/accounts_spec.rb
  spec/api/v1/phones_spec.rb
  spec/support/capybara.rb
Labels: PR: approved

#391 Feature/account confirm api
  app/controllers/api/v1/accounts.rb
  app/helpers/view_helper.rb
  app/views/devise/mailer/confirmation_instructions.html.erb
  app/views/devise/mailer/reset_password_instructions.html.erb
  spec/api/v1/accounts_spec.rb
Labels: PR: approved

#405 Update 1.7.0 migration steps notes
  docs/releases/1.7.0.md
Labels: PR: approved

#410 Events API, Plugins
  .gitignore
  Gemfile
  Gemfile.lock
  bin/install_plugins
  bin/uninstall_plugins
  config/application.rb
  config/initializers/exception_reporting.rb
  config/plugins.rb
  config/plugins.yml.example
Labels: PR: WIP

#414 Add labels to admin panel with CRUD
  .rubocop.yml
  app/controllers/admin/labels_controller.rb
  app/controllers/admin/profiles_controller.rb
  app/models/label.rb
  app/views/admin/labels/_form.html.erb
  app/views/admin/labels/edit.html.erb
  app/views/admin/labels/new.html.erb
  app/views/admin/profiles/show.html.erb
  config/routes.rb
Labels: PR: approved

#423 Implement send code API
  app/controllers/api/v1/phones.rb
  app/models/phone.rb
Labels: PR: approved

#431 Show level and labels on account index page
  app/helpers/view_helper.rb
  app/views/admin/accounts/index.html.erb
Labels: PR: approved

#430 Migrate application levels logic to use labels
  app/api/user_api/v1/phones.rb
  app/controllers/phones_controller.rb
  app/models/account.rb
  app/models/profile.rb
  spec/api/user_api/v1/phones_spec.rb
  spec/controllers/admin/profiles_controller_spec.rb
  spec/controllers/documents_controller_spec.rb
  spec/controllers/phones_controller_spec.rb
  spec/controllers/profiles_controller_spec.rb
  spec/features/phone_verification_spec.rb
  spec/models/label_spec.rb
  spec/models/profile_spec.rb
  spec/spec_helper.rb
  spec/support/helpers.rb
Labels: PR: approved
