Repository openware/barong, pull requests merged in 2018-06, with the labels that each got.

#511 Change password security error message
  config/locales/devise.security_extension.en.yml
  spec/api/user_api/v1/accounts_spec.rb
Labels: PR: approved

#471 Ci bump pagination 1 5
  ci/bump.rb
Labels: PR: approved, type: enhancement, v1.5

#516 Add CORS middleware
  .rubocop.yml
  app/api/user_api/v1/base.rb
  app/api/user_api/v1/cors/middleware.rb
  config/initializers/cors.rb
  spec/api/user_api/v1/cors_spec.rb
  spec/api/user_api/v1/documents_spec.rb
Labels: PR: approved, Priority: high, v1.8

#519 Remove rack-cors
  Gemfile
  Gemfile.lock
  config/application.rb
Labels: PR: approved

#528 Set events with correct devise tokens
  app/mailers/account_mailer.rb
  app/models/account.rb
  docs/specs/event_api.md
Labels: PR: approved, Priority: high, v1.8

#481 Fix labels bug with changing scope
  app/models/label.rb
  spec/models/label_spec.rb
Labels: PR: approved, v1.8

#515 Add localization for grape required fields
  app/api/user_api/v1/accounts.rb
  app/api/user_api/v1/sessions.rb
  config/locales/en.yml
  spec/api/management_api_v1/labels_spec.rb
  spec/api/user_api/v1/accounts_spec.rb
  spec/api/user_api/v1/documents_spec.rb
  spec/api/user_api/v1/phones_spec.rb
  spec/api/user_api/v1/profiles_spec.rb
  spec/api/user_api/v1/security_spec.rb
  spec/api/user_api/v1/sessions_spec.rb
Labels: PR: approved

#473 Feature/add favicon to website
  app/controllers/admin/websites_controller.rb
  app/helpers/application_helper.rb
  app/models/website.rb
  app/views/admin/websites/_form.html.erb
  app/views/layouts/admin.html.erb
  app/views/layouts/application.html.erb
  app/views/layouts/devise.html.erb
  app/views/layouts/doorkeeper/admin.html.erb
  db/migrate/20180516142429_add_favicon_to_websites.rb
  db/schema.rb
Labels: PR: approved, v1.8

#535 Fix issues with levels
  app/helpers/application_helper.rb
  app/models/label.rb
  app/views/admin/accounts/show.html.erb
  lib/tasks/add_labels_according_to_level.rake
Labels: PR: approved

#527 Add otp sign endpoint
  app/api/management_api/v1/base.rb
  app/api/management_api/v1/otp.rb
  app/api/user_api/v1/session_jwt_generator.rb
  app/models/account.rb
  config/initializers/doorkeeper.rb
  config/locales/en.yml
  config/management_api_v1.yml
  docs/api/management_api_v1.md
  lib/barong/security/access_token.rb
  spec/api/management_api_v1/otp_spec.rb
  spec/api/user_api/v1/sessions_spec.rb
  spec/factories/account.rb
  spec/support/helpers.rb
Labels: PR: approved

#533 Feature/admin disable 2fa
  .rubocop.yml
  app/api/user_api/v1/accounts.rb
  app/controllers/admin/accounts_controller.rb
  app/views/admin/accounts/show.html.erb
  config/routes.rb
  spec/api/user_api/v1/accounts_spec.rb
Labels: PR: approved

#531 Add endpoint for resend confirmations
  app/api/user_api/v1/accounts.rb
  docs/index.md
  spec/api/user_api/v1/accounts_spec.rb
Labels: PR: approved

#477 Add validations for profile, add datepicker and country select for profile admin panel
  app/api/user_api/v1/profiles.rb
  app/assets/javascripts/admin.js
  app/assets/stylesheets/admin.scss
  app/helpers/country_helper.rb
  app/models/document.rb
  app/models/profile.rb
  app/views/admin/profiles/_form.html.erb
  spec/api/user_api/v1/profiles_spec.rb
  spec/controllers/admin/profiles_controller_spec.rb
  spec/factories/profile.rb
  spec/models/profile_spec.rb
Labels: PR: approved, v1.8

#522 Check 2FA on Barong session api, stub vault request if vault server is down
  app/api/user_api/v1/sessions.rb
  spec/api/user_api/v1/sessions_spec.rb
Labels: PR: approved, Priority: high

#486 Add account get endpoint for managment API
  app/api/entities/account_with_profile.rb
  app/api/entities/profile.rb
  app/api/management_api/v1/accounts.rb
  app/api/management_api/v1/base.rb
  app/api/management_api/v1/jwt_authentication_middleware.rb
  docs/api/management_api_v1.md
  spec/api/management_api_v1/accounts_spec.rb
  spec/controllers/admin/profiles_controller_spec.rb
  spec/factories/account.rb
Labels: PR: approved, v1.8

#537 Add account uid to system.notification.account
  app/mailers/account_mailer.rb
  app/models/label.rb
  docs/specs/event_api.md
Labels: PR: approved, Priority: high

#504 Get international number from phonelib directly
  Gemfile.lock
  app/api/user_api/v1/helpers.rb
  app/api/user_api/v1/phones.rb
  app/controllers/phones_controller.rb
  lib/phone_utils.rb
  spec/api/user_api/v1/phones_spec.rb
  spec/controllers/phones_controller_spec.rb
Labels: PR: approved

#539 Management api config generation from template
  .gitignore
  .travis.yml
  bin/init_config
  config/templates/management_api_v1.yml.erb
  config/templates/plugins.yml.erb
Labels: PR: approved

#549 Moved documentation files
  docs/api/api.md
  docs/api/api_keys.md
  docs/api/event_api.md
  lib/tasks/slate.rake
Labels: PR: approved

#542 Compute code coverage report
  .gitignore
  .travis.yml
  Gemfile
  Gemfile.lock
  spec/spec_helper.rb
Labels: PR: approved

#550 Add email for Event API system.account.reset_password_token, system.account.unlock_token events, system.document.verified, system.document.rejected
  app/mailers/account_mailer.rb
  app/models/label.rb
  docs/api/event_api.md
Labels: PR: approved

#554 Fixes docker image build
  Dockerfile
Labels: PR: approved

#544 Lockable in API
  app/api/user_api/v1/accounts.rb
  app/api/user_api/v1/sessions.rb
  app/models/account.rb
  app/models/profile.rb
  app/views/devise/mailer/unlock_instructions.html.erb
  docs/api/api.md
  spec/api/user_api/v1/accounts_spec.rb
  spec/api/user_api/v1/sessions_spec.rb
Labels: PR: approved

#552 Fix wrong field in accounts/get
  app/api/entities/account_with_profile.rb
  spec/api/management_api_v1/accounts_spec.rb
Labels: PR: approved
