Repository openware/barong, pull requests merged in 2019-03, with the labels that each got.

#786 Add Entities::Activity model, include it Entities::UserWithFullInfo
  app/api/v2/base.rb
  app/api/v2/entities/activity.rb
  app/api/v2/entities/user_with_full_info.rb
  spec/api/v2/entities/activities_spec.rb
Labels: PR: approved, v2

#789 Use 'paginate' on api/v2/admin/users/search
  app/api/v2/admin/users.rb
Labels: PR: approved, v2

#804 API user activity sort desc
  app/api/v2/resource/users.rb
  spec/api/v2/resource/users_spec.rb
  spec/factories/activity.rb
Labels: PR: approved, v2

#807 Allow to list API Keys without providing OTP code
  app/api/v2/resource/api_keys.rb
  spec/api/v2/resource/api_keys_spec.rb
Labels: PR: approved, v2

#791 Improve language support in event API, add domain info inside event
  app/api/v2/identity/users.rb
  app/api/v2/identity/utils.rb
  app/api/v2/resource/users.rb
  config/initializers/event_api.rb
Labels: PR: approved, type: feature, v2

#800 Add ability to search users by labels
  app/api/v2/admin/users.rb
  config/credentials.yml.enc
  docs/errors.md
  spec/api/v2/admin/users_spec.rb
  spec/api/v2/management/labels_spec.rb
Labels: PR: approved, v2

#795 Add auto-generating doc support
  .drone.yml
  bin/gendocs
  config/initializers/versioning.rb
  docs/management.md
  docs/rest_api.json
  docs/rest_api.md
Labels: frozen, v2

#790 Allow to configure multiple CORS at barong
  app/api/user_api/v1/cors/middleware.rb
  config/initializers/cors.rb
  spec/api/user_api/v1/cors_spec.rb
Labels: PR: approved, v1.8

#815 Add opportunity to get list of users by management API
  app/api/v2/management/users.rb
  spec/api/v2/management/jwt_authentication_middleware_spec.rb
  spec/api/v2/management/labels_spec.rb
  spec/api/v2/management/users_spec.rb
  spec/support/api_helpers.rb
Labels: PR: approved
