Repository openware/barong, pull requests merged in 2019-06, with the labels that each got.

#838 Update seeds.yml
  config/seeds.yml
Labels: PR: approved

#842 Use FullInfo instead of WithProfile to add documents array in response
  app/api/v2/admin/users.rb
  spec/api/v2/admin/users_spec.rb
Labels: PR: approved

#841 Remove activities from full_info entity
  app/api/v2/entities/user_with_full_info.rb
  spec/api/v2/entities/user_with_full_spec.rb
Labels: PR: approved

#840 Fix nil language problem in case of empty string and upcased param
  app/api/v2/identity/utils.rb
  app/api/v2/resource/users.rb
  spec/api/v2/identity/users_spec.rb
Labels: PR: approved

#839 Return empty array instead of 404 error after filtering
  app/api/v2/admin/users.rb
  spec/api/v2/admin/users_spec.rb
Labels: PR: approved

#823 Make :doc_expire an optional field
  app/api/v2/resource/documents.rb
  app/models/document.rb
  config/initializers/document.rb
  docs/errors.md
  lib/barong/app.rb
  spec/api/v2/resource/documents_spec.rb
Labels: PR: approved

#829 Disable APIKeys when user state or otp changes
  app/api/v2/admin/users.rb
  app/models/user.rb
  spec/api/v2/admin/users_spec.rb
  spec/api/v2/auth_spec.rb
Labels: PR: approved

#835 Admin Auditor
  .codeclimate.yml
  app/api/v2/admin/activities.rb
  app/api/v2/admin/permissions.rb
  app/api/v2/admin/users.rb
  app/api/v2/entities/admin_activity.rb
  app/api/v2/identity/utils.rb
  app/api/v2/queries/activity_filter.rb
  app/api/v2/resource/users.rb
  app/api/v2/resource/utils.rb
  app/models/activity.rb
  config/seeds.yml
  db/migrate/20190529114214_changes_in_activities_table.rb
  db/schema.rb
  lib/barong/activity_logger.rb
  lib/barong/authorize.rb
  lib/barong/seed.rb
  spec/api/v2/admin/activities_spec.rb
  spec/api/v2/auth_spec.rb
  spec/factories/activity.rb
  spec/models/activity_spec.rb
  spec/support/api_helpers.rb
Labels: PR: approved, type: feature

#852 Split and refactor auth spec, add sync auditor for test env
  lib/barong/activity_logger.rb
  lib/barong/authorize.rb
  spec/api/v2/auth/audit_spec.rb
  spec/api/v2/auth/auth_spec.rb
  spec/api/v2/auth/rbac_spec.rb
  spec/api/v2/auth_spec.rb
Labels: PR: approved

#853 Add missing data field in activity logger
  lib/barong/activity_logger.rb
  spec/api/v2/auth/audit_spec.rb
Labels: PR: approved

#850 Changes in admin API module
  app/api/v2/admin/activities.rb
  app/api/v2/admin/permissions.rb
  app/api/v2/admin/users.rb
  docs/errors.md
  spec/api/v2/admin/activities_spec.rb
  spec/api/v2/admin/users_spec.rb
Labels: PR: approved

#851 Add GET /identity/version endpoint
  app/api/v2/identity/general.rb
Labels: PR: approved

#856 Add docs in bump and update redeploy step
  .drone.yml
Labels: PR: approved

#849 Use JSON logs in production
  app/api/v2/base.rb
  app/api/v2/management/base.rb
  config/application.rb
  config/environments/production.rb
  lib/barong/json_log_formatter.rb
Labels: PR: approved

#857 Fix /api/v2/admin/users/update
  app/api/v2/admin/users.rb
  spec/api/v2/admin/users_spec.rb
Labels: peer:approved
