Repository openware/barong, pull requests merged in 2019-05, with the labels that each got.

#811 Add DELETE /resource/users/me to allow user to block his account
  app/api/v2/identity/sessions.rb
  app/api/v2/resource/users.rb
  docs/errors.md
  docs/event_api.md
  spec/api/v2/resource/users_spec.rb
Labels: PR: approved, v2

#826 Added API call to get users with pending documents
  app/api/v2/admin/users.rb
  spec/api/v2/admin/users_spec.rb
Labels: PR: approved

#831 Add endpoint to list all user's phones
  app/api/v2/resource/phones.rb
  spec/api/v2/resource/phones_spec.rb
Labels: PR: approved

#827 Add management otp sign endpoint and specs
  app/api/v2/management/base.rb
  app/api/v2/management/otp.rb
  spec/api/v2/management/otp_spec.rb
Labels: PR: approved

#820 Avoid nil language bug on user creation event
  app/api/v2/identity/users.rb
  spec/api/v2/identity/users_spec.rb
Labels: PR: approved

#824 Add GET /labels/list to return key, value, scope of all existing labels
  Gemfile
  app/api/v2/admin/users.rb
  app/api/v2/entities/label.rb
  spec/api/v2/admin/users_spec.rb
Labels: PR: approved

#819 Permissions & roles, seed feature and authz logic
  app/api/v2/admin/base.rb
  app/api/v2/admin/permissions.rb
  app/models/permission.rb
  app/models/user.rb
  config/seeds.yml
  db/migrate/20190318133453_create_permissions.rb
  db/schema.rb
  db/seeds.rb
  lib/barong/app.rb
  lib/barong/authorize.rb
  lib/barong/seed.rb
  spec/api/v2/admin/users_spec.rb
  spec/api/v2/auth_spec.rb
  spec/api/v2/cors/cors_spec.rb
  spec/api/v2/entities/activities_spec.rb
  spec/api/v2/entities/labels_spec.rb
  spec/api/v2/identity/sessions_spec.rb
  spec/api/v2/identity/users_spec.rb
  spec/api/v2/management/labels_spec.rb
  spec/api/v2/management/otp_spec.rb
  spec/api/v2/management/users_spec.rb
  spec/api/v2/resource/api_keys_spec.rb
  spec/api/v2/resource/documents_spec.rb
  spec/api/v2/resource/labels_spec.rb
  spec/api/v2/resource/phones_spec.rb
  spec/api/v2/resource/profiles_spec.rb
  spec/api/v2/resource/users_spec.rb
  spec/factories/permission.rb
  spec/lib/barong/seed_spec.rb
  spec/models/activity_spec.rb
  spec/models/document_spec.rb
  spec/models/label_spec.rb
  spec/models/profile_spec.rb
  spec/models/user_spec.rb
Labels: PR: approved, type: feature

#828 Added admin endpoints to get activities
  .gitignore
  app/api/v2/admin/activities.rb
  app/api/v2/admin/base.rb
  app/api/v2/entities/activity_with_user.rb
  app/api/v2/queries/activity_filter.rb
  spec/api/v2/admin/activities_spec.rb
  spec/api/v2/queries/activity_filter_spec.rb
Labels: PR: approved

#830 Add ability to get list of users with profile
  app/api/v2/admin/users.rb
  spec/api/v2/admin/users_spec.rb
Labels: PR: approved

#834 Add metrics namespace in admin module
  app/api/v2/admin/activities.rb
  app/api/v2/admin/base.rb
  app/api/v2/admin/metrics.rb
  app/api/v2/identity/users.rb
  app/api/v2/queries/activity_filter.rb
  app/models/activity.rb
  spec/api/v2/admin/metrics_spec.rb
  spec/factories/activity.rb
Labels: PR: approved

#833 Add ability to filter by multiple fields
  app/api/v2/admin/users.rb
  app/api/v2/queries/user_filter.rb
  spec/api/v2/admin/users_spec.rb
Labels: PR: approved
