Repository openware/barong, pull requests merged in 2019-09, with the labels that each got.

#904 Update Barong::App validations
  app/api/v2/resource/documents.rb
  config.ru
  config/initializers/barong.rb
  config/initializers/cors.rb
  config/initializers/document.rb
  config/initializers/phone.rb
  config/initializers/redis_store.rb
  config/initializers/sessions_store.rb
  lib/barong/app.rb
  spec/api/v2/resource/documents_spec.rb
  spec/factories/profile.rb
Labels: peer:approved, type: enhancement

#910 Ability create Profile with empty fields. Add state to Profile model.
  app/api/v2/entities/profile.rb
  app/api/v2/resource/profiles.rb
  app/models/profile.rb
  db/migrate/20190902032709_add_state_profiles.rb
  db/schema.rb
  spec/api/v2/resource/profiles_spec.rb
  spec/models/profile_spec.rb
  spec/spec_helper.rb
Labels: Priority: high, peer:approved, ready to merge

#914 Fix rollback to pending state, add missing :data in entities
  app/api/v2/entities/user_with_full_info.rb
  app/api/v2/entities/user_with_kyc.rb
  app/api/v2/entities/user_with_profile.rb
  app/models/user.rb
  spec/api/v2/identity/users_spec.rb
  spec/api/v2/management/users_spec.rb
  spec/models/user_spec.rb
Labels: Priority: high, ready to merge, type: bug

#915 Support 'if not exist - create' logic on labels update
  app/api/v2/admin/users.rb
  app/api/v2/management/labels.rb
  spec/api/v2/admin/users_spec.rb
  spec/api/v2/management/labels_spec.rb
Labels: Priority: low, ready to merge

#917 UPDATES: sessions delete, permissions update, log error on 500
  app/api/v2/admin/permissions.rb
  app/api/v2/exception_handlers.rb
  app/api/v2/identity/sessions.rb
  spec/api/v2/admin/permissions_spec.rb
  spec/api/v2/identity/sessions_spec.rb
Labels: peer:approved, ready to merge

#919 Add :upload in list of params to be filtered
  config/initializers/filter_parameter_logging.rb
Labels: ready to merge

#912 Fix structure of event API messages
  app/api/v2/identity/users.rb
  app/api/v2/identity/utils.rb
  app/api/v2/resource/users.rb
  app/models/label.rb
  docs/event_api.md
  spec/api/v2/identity/users_spec.rb
Labels: PR: review needed, Priority: high

#918 Handle Vault errors on POST /api/v2/resource/api_keys
  app/api/v2/entities/api_key.rb
  app/api/v2/resource/api_keys.rb
  spec/api/v2/resource/api_keys_spec.rb
Labels: peer:approved, ready to merge

#920 Add ability to restrict by geoip
  Dockerfile
  Gemfile
  Gemfile.lock
  app/models/restriction.rb
  config/initializers/barong.rb
  config/initializers/barong_config.rb
  config/initializers/sessions_store.rb
  lib/barong/app.rb
  lib/barong/authorize.rb
  lib/barong/geo_ip.rb
  spec/api/v2/auth/audit_spec.rb
  spec/api/v2/auth/auth_spec.rb
  spec/api/v2/auth/rbac_spec.rb
  spec/api/v2/auth/restriction_spec.rb
  spec/api/v2/identity/sessions_spec.rb
  spec/api/v2/identity/users_spec.rb
  spec/support/geoip_context.rb
Labels: peer:approved, ready to merge

#921 Avoid no method error UTC for nil entities
  app/api/v2/entities/activity.rb
  app/api/v2/entities/activity_with_user.rb
  app/api/v2/entities/admin_activity.rb
  app/api/v2/entities/api_key.rb
  app/api/v2/entities/base.rb
  app/api/v2/entities/document.rb
  app/api/v2/entities/label.rb
  app/api/v2/entities/phone.rb
  app/api/v2/entities/profile.rb
  app/api/v2/entities/user.rb
  app/api/v2/entities/user_with_full_info.rb
  app/api/v2/entities/user_with_kyc.rb
  app/api/v2/entities/user_with_profile.rb
Labels: ready to merge

#916 Add system.session.create event with user and request_ip data
  app/api/v2/identity/sessions.rb
  app/api/v2/identity/utils.rb
  docs/event_api.md
  spec/api/v2/identity/sessions_spec.rb
Labels: peer:approved, ready to merge

#934 Update seeds.yml
  config/seeds.yml
Labels: peer:approved, ready to merge

#933 Event API changes: remove blocking check for on_update events
  config/barong.yml
  docs/event_api.md
  lib/barong/event_api.rb
  spec/models/user_spec.rb
Labels: ready to merge

#932 Simple GET levels requirements endpoint for admin
  app/api/v2/admin/base.rb
  app/api/v2/admin/levels.rb
  app/api/v2/base.rb
  app/api/v2/entities/level.rb
  spec/api/v2/admin/levels_spec.rb
Labels: PR: review needed, ready to merge

#930 Get rid of serialize: JSON, accept metadata as json instead of pure hash
  app/api/v2/admin/profiles.rb
  app/api/v2/management/documents.rb
  app/api/v2/resource/documents.rb
  app/api/v2/resource/profiles.rb
  app/models/document.rb
  app/models/profile.rb
  spec/api/v2/resource/documents_spec.rb
  spec/api/v2/resource/profiles_spec.rb
Labels: PR: review needed, ready to merge

#935 Define DocumentTypes class for flexible doc type configuration
  app/models/document.rb
  config/barong.yml
  config/initializers/document_types.rb
  spec/initializers/document_types.spec.rb
Labels: ready to merge

#936 Make labels acts_as_eventable on: [create update]
  app/models/label.rb
Labels: ready to merge

#937 Add missing labels event api documentation
  app/models/label.rb
  docs/event_api.md
  spec/models/label_spec.rb
Labels: ready to merge

#928 Change twilio API
  Gemfile
  Gemfile.lock
  app/api/v2/resource/api_keys.rb
  app/api/v2/resource/phones.rb
  app/models/phone.rb
  app/services/twilio_sms_send_service.rb
  app/services/twilio_verify_service.rb
  config/initializers/phone.rb
  lib/barong/mock_sms.rb
  spec/api/v2/resource/phones_spec.rb
Labels: PR: review needed, ready to merge

#903 Add session autorenew
  app/controllers/authorize_controller.rb
  spec/api/v2/auth/auth_spec.rb
Labels: peer:approved

#943 Use uid instead of id on profile update && delete api
  app/api/v2/admin/profiles.rb
  spec/api/v2/admin/profiles_spec.rb
Labels: ready to merge
