Repository openware/barong, pull requests merged in 2019-07, with the labels that each got.

#862 Update Readme
  README.md
Labels: peer:approved

#870 Add verb PATCH and ALL for admin audit && Update permission seeds
  app/api/v2/admin/permissions.rb
  config/seeds.yml
  spec/api/v2/admin/permissions_spec.rb
  spec/factories/permission.rb
Labels: peer:approved

#865 Make profile act_as_eventable on create
  app/api/v2/resource/profiles.rb
  app/models/label.rb
  app/models/profile.rb
  docs/event_api.md
  spec/api/v2/resource/profiles_spec.rb
Labels: peer:approved

#864 Add filter/users in labels management api module
  README.md
  app/api/v2/management/labels.rb
  app/api/v2/queries/user_with_label_filter.rb
  spec/api/v2/management/labels_spec.rb
Labels: peer:approved

#861 Support pagination & timestamp filtering on post '/list' management API
  app/api/v2/management/users.rb
  spec/api/v2/management/users_spec.rb
Labels: peer:approved

#871 Make documents act_as_eventable on create
  app/models/document.rb
  docs/event_api.md
  spec/api/v2/resource/documents_spec.rb
Labels: peer:approved

#872 Add optional :extended UserWithFullInfo entity in post /get management
  app/api/v2/management/users.rb
  spec/api/v2/management/users_spec.rb
Labels: peer:approved

#836 [ci skip] Release 2.2.0
  CHANGELOG.md
  VERSION
Labels: peer:approved

#874 Feature: Add redeploy on devkube step to drone
  .drone.yml
Labels: PR: review needed

#881 Allow pending user to open session
  app/api/v2/identity/sessions.rb
  spec/api/v2/identity/sessions_spec.rb
Labels: PR: review needed

#877 Add ability to configure phone verification sms content
  app/models/phone.rb
  config/initializers/phone.rb
  spec/api/v2/resource/phones_spec.rb
Labels: PR: review needed, type: feature

#884 Extend doc_type inclusion list, make validation case insensitive
  app/models/document.rb
  spec/api/v2/resource/documents_spec.rb
  spec/models/document_spec.rb
Labels: PR: review needed
