Repository openware/barong, pull requests merged in 2019-01, with the labels that each got.

#705 Small fixes of event api and lock feature
  app/api/user_api/v1/sessions.rb
  config/initializers/event_api.rb
  config/locales/devise.en.yml
  spec/api/user_api/v1/sessions_spec.rb
Labels: PR: approved, v1.9

#704 Small fixes of event api and lock feature
  app/api/user_api/v1/sessions.rb
  config/initializers/event_api.rb
  config/locales/devise.en.yml
  spec/api/user_api/v1/sessions_spec.rb
Labels: PR: approved, v1.8

#706 Add users entity on login and /me
  .travis.yml
  app/api/v2/base.rb
  app/api/v2/entities/user.rb
  app/api/v2/identity/sessions.rb
  app/api/v2/resource/users.rb
Labels: PR: approved, v2

#709 Add referral_id to users table and as an optional param on signup
  app/api/v2/identity/users.rb
  app/models/user.rb
  db/migrate/20190108115333_add_referral_id_to_users_table.rb
  db/schema.rb
  spec/api/v2/identity/users_spec.rb
Labels: PR: approved, PR: review needed

#707 Updating to ruby 2.6.0
  .codeclimate.yml
  .drone.yml
  .ruby-version
  Dockerfile
  Gemfile
  Gemfile.lock
Labels: PR: approved, v2

#726 Change regex validations to support different language characters
  app/models/profile.rb
  spec/api/v2/resource/profiles_spec.rb
  spec/models/profile_spec.rb
Labels: PR: approved, v2

#724 Fix change password api action from post to put
  app/api/v2/resource/users.rb
  spec/api/v2/resource/users_spec.rb
Labels: PR: approved, v2

#722 Add admin api functionality on user update
  app/api/v2/admin/users.rb
  app/api/v2/base.rb
  app/api/v2/entities/phone.rb
  app/api/v2/entities/user_with_full_info.rb
  spec/api/v2/admin/users_spec.rb
Labels: PR: approved, v2

#716 Add an ability to specify CORS(multiple)
  .codeclimate.yml
  Gemfile
  Gemfile.lock
  app/api/v2/resource/users.rb
  config.ru
  config/application.rb
  config/initializers/cors.rb
  lib/barong/cors/validations.rb
  spec/api/v2/cors/cors_spec.rb
  spec/api/v2/cors/validations_spec.rb
Labels: PR: approved, v2

#686 AuthZ move to controller and lib
  app/api/v2/identity/sessions.rb
  app/api/v2/identity/utils.rb
  app/controllers/authorize_controller.rb
  app/models/api_key.rb
  app/services/api_keys_verifier.rb
  config/authz_rules.yml
  config/routes.rb
  lib/barong/authorize.rb
  spec/api/v2/auth_spec.rb
  spec/api/v2/identity/sessions_spec.rb
Labels: PR: approved, PR: review needed, type: feature, v2

#713 Split swagger doc into restful and management
  app/api/v2/base.rb
  app/api/v2/management/base.rb
  app/api/v2/management/jwt_authentication_middleware.rb
  barong_api_v2.md
  docs/management.json
  docs/management.md
  docs/rest_api.json
  docs/rest_api.md
  spec/api/v2/auth_spec.rb
Labels: in progress, v2

#737 Add storage envs in config store and update fetch logic
  config/initializers/carrierwave.rb
Labels: PR: approved, v2

#730 Fix change code on phone initialize, remove code from logs
  app/models/phone.rb
  spec/api/v2/resource/phones_spec.rb
Labels: PR: approved, v2

#734 Configure redis and add JTI blacklisting
  Gemfile
  Gemfile.lock
  app/api/v2/identity/users.rb
  app/api/v2/identity/utils.rb
  config/environments/development.rb
  config/initializers/redis_store.rb
Labels: PR: approved, v2

#739 Fix Barong::CORS load problem in production env
  config.ru
Labels: PR: approved, v2

#742 Add missing user details in 2fa login response
  app/api/v2/identity/sessions.rb
Labels: PR: approved, type: fix, v2
