Repository openware/barong, pull requests merged in 2019-08, with the labels that each got.

#885 Add rake task for load users and referrals
  docs/tasks/import.md
  lib/tasks/import_users.rake
Labels: peer:approved, type: feature

#816 Simple rake task to create users and api keys
  .drone.yml
  .ruby-version
  Dockerfile
  Gemfile
  Gemfile.lock
  app/services/captcha_service.rb
  barong_api_v2.md
  config/initializers/barong.rb
  config/initializers/event_api.rb
  config/initializers/jwt.rb
  lib/barong/event_api.rb
  lib/tasks/generate.rake
  spec/api/v2/resource/labels_spec.rb
  spec/factories/activity.rb
  spec/factories/label.rb
Labels: frozen

#891 Add Restrictions
  app/api/v2/admin/activities.rb
  app/api/v2/admin/base.rb
  app/api/v2/admin/permissions.rb
  app/api/v2/admin/restrictions.rb
  app/api/v2/admin/users.rb
  app/models/restriction.rb
  app/services/secret_storage.rb
  db/migrate/20190813112503_create_restrictions.rb
  db/schema.rb
  lib/barong/authorize.rb
  spec/api/v2/admin/permissions_spec.rb
  spec/api/v2/admin/restrictions_spec.rb
  spec/api/v2/auth/audit_spec.rb
  spec/api/v2/auth/auth_spec.rb
  spec/api/v2/auth/rbac_spec.rb
  spec/api/v2/auth/restriction_spec.rb
  spec/factories/restriction.rb
  spec/models/label_spec.rb
  spec/models/profile_spec.rb
  spec/models/restrictions_spec.rb
  spec/models/user_spec.rb
  spec/spec_helper.rb
Labels: peer:approved

#893 Add ability to configure uid prefix
  app/models/user.rb
  config/initializers/barong.rb
  lib/barong/app.rb
  spec/models/user_spec.rb
Labels: peer:approved, ready to merge, type: feature

#882 Add ability to get referral uid && Expose referral_uid in user, user_with_profile, user_with_full_info entities
  app/api/v2/entities/user.rb
  app/api/v2/entities/user_with_full_info.rb
  app/api/v2/entities/user_with_profile.rb
  app/models/user.rb
  spec/api/v2/admin/users_spec.rb
  spec/api/v2/management/users_spec.rb
  spec/models/user_spec.rb
Labels: PR: review needed, peer:approved, ready to merge

#894 Management API to push documents for user
  app/api/v2/management/base.rb
  app/api/v2/management/documents.rb
  spec/api/v2/management/documents_spec.rb
Labels: PR: review needed, ready to merge

#867 Updating to ruby 2.6.3 and rails 5.2.3
  Dockerfile
  Gemfile
  Gemfile.lock
Labels: ready to merge

#895 Update models' annotations
  app/models/activity.rb
  app/models/api_key.rb
  app/models/document.rb
  app/models/label.rb
  app/models/level.rb
  app/models/permission.rb
  app/models/phone.rb
  app/models/profile.rb
  app/models/user.rb
Labels: peer:approved, ready to merge, type: enhancement

#901 Small fixes in document and profile model (#887)
  app/api/v2/resource/documents.rb
  app/models/profile.rb
  config/initializers/document.rb
  spec/api/v2/resource/documents_spec.rb
  spec/api/v2/resource/profiles_spec.rb
Labels: ready to merge

#902 Add endpoint for delete restriction
  app/api/v2/admin/restrictions.rb
  spec/api/v2/admin/restrictions_spec.rb
  spec/api/v2/admin/users_spec.rb
  spec/factories/profile.rb
Labels: peer:approved, ready to merge, type: feature
