Repository openware/barong, pull requests merged in 2020-06, with the labels that each got.

#1086 Feature: Add email filters
  app/services/event_mailer.rb
  config/mailer.yml
  spec/services/event_mailer_spec.rb
Labels: peer:approved

#1102 Enhancement: JWT expirating and Cache expiration policy improve
  app/api/v2/exception_handlers.rb
  app/api/v2/identity/users.rb
  app/api/v2/identity/utils.rb
  config/initializers/barong.rb
  docs/configuration.md
  lib/barong/authorize.rb
  lib/barong/jwt.rb
  spec/api/v2/identity/users_spec.rb
Labels: PR: review needed

#1103 Enhancement: raise error on Mysql2::Error::ConnectionError in the mailer
  app/services/event_mailer.rb
Labels: PR: review needed, need qa
