Repository openware/barong, pull requests merged in 2020-05, with the labels that each got.

#1066 Refactor: remove nonsense failed login activity on empty otp
  app/api/v2/identity/sessions.rb
Labels: PR: review needed

#1065 Enhancement: add management API - create profile, update :data field
  app/api/v2/management/base.rb
  app/api/v2/management/profiles.rb
  app/api/v2/management/users.rb
  spec/api/v2/management/profiles_spec.rb
  spec/api/v2/management/users_spec.rb
Labels: PR: review needed, type: feature

#1060 Enhancement: remove lang param from APIs, stick to user.language logic
  app/api/v2/identity/users.rb
  app/api/v2/identity/utils.rb
  app/api/v2/resource/users.rb
  app/models/user.rb
  spec/api/v2/identity/users_spec.rb
Labels: PR: review needed

#1061 Feature: introduce category of restrictions, restrictions as firewall
  app/api/v2/admin/restrictions.rb
  app/api/v2/identity/users.rb
  app/controllers/authorize_controller.rb
  app/models/activity.rb
  app/models/api_key.rb
  app/models/data_storage.rb
  app/models/document.rb
  app/models/label.rb
  app/models/permission.rb
  app/models/phone.rb
  app/models/profile.rb
  app/models/restriction.rb
  app/models/user.rb
  config/seeds.yml
  db/migrate/20200429082843_add_code_and_type_in_restrictions_table.rb
  db/schema.rb
  db/seeds.rb
  docs/restrictions.md
  lib/barong/authorize.rb
  lib/barong/seed.rb
  spec/api/v2/admin/restrictions_spec.rb
  spec/api/v2/auth/restriction_spec.rb
  spec/api/v2/identity/users_spec.rb
  spec/factories/api_keys.rb
  spec/factories/phones.rb
  spec/lib/barong/seed_spec.rb
  spec/models/activity_spec.rb
  spec/models/document_spec.rb
  spec/models/label_spec.rb
  spec/models/level_spec.rb
  spec/models/profile_spec.rb
  spec/models/restrictions_spec.rb
  spec/models/user_spec.rb
Labels: PR: review needed, QA Approved

#1052 Feature: admin endpoint to retrieve user api keys
  app/api/v2/admin/api_keys.rb
  app/api/v2/admin/base.rb
  spec/api/v2/admin/api_keys_spec.rb
Labels: PR: review needed, QA Approved

#1073 Update .drone.yml
  .drone.yml
Labels: ready to merge
