Repository openware/barong, pull requests merged in 2020-08, with the labels that each got.

#1124 Change naming to barong.postmaster.event.mailer and turn off manual_ack for events
  app/services/event_mailer.rb
Labels: ready to merge

#1119 Feature: add filters for /resource/users/activity/all endpoint
  app/api/v2/resource/users.rb
  spec/api/v2/resource/users_spec.rb
Labels: ready to merge

#1098 Add ability for admin to create comments
  app/api/v2/admin/users.rb
  app/api/v2/entities/comment.rb
  app/api/v2/entities/user_with_kyc.rb
  app/models/comment.rb
  app/models/user.rb
  db/migrate/20200609144734_create_comments.rb
  db/schema.rb
  spec/api/v2/admin/users_spec.rb
  spec/api/v2/management/users_spec.rb
Labels: QA Approved, peer:approved, ready to merge

#1090 Feature: post admin/profiles, 2-admin profile approval
  app/api/v2/admin/profiles.rb
  config/barong.yml
  config/initializers/barong.rb
  db/migrate/20200602075906_add_author_to_profiles.rb
  db/schema.rb
  docs/general/profiles.md
  spec/api/v2/admin/profiles_spec.rb
  spec/factories/profile.rb
Labels: peer:approved, ready to merge

#1114 Feature: ability to customize email template logo
  app/mailers/postmaster.rb
  app/services/event_mailer.rb
  app/views/postmaster/deposit_accepted.en.html.erb
  app/views/postmaster/email_confirmation.en.html.erb
  app/views/postmaster/email_confirmation.ru.html.erb
  app/views/postmaster/label.en.html.erb
  app/views/postmaster/new_beneficiary.en.html.erb
  app/views/postmaster/password_reset.en.html.erb
  app/views/postmaster/password_reset.ru.html.erb
  app/views/postmaster/session_create.en.html.erb
  app/views/postmaster/withdraw_succeed.en.html.erb
  config/initializers/barong.rb
  spec/mailers/postmaster_spec.rb
Labels: ready to merge

#1130 Add structure.sql
  db/structure.sql
Labels: ready to merge

#1131 Add structure.sql
  db/schema.rb
  db/structure.sql
Labels: ready to merge

#1132 Handle OpenURI::HTTPError 404 && avoid OpenURI StringIO creation
  app/workers/kyc/kycaid/address_worker.rb
  app/workers/kyc/kycaid/document_worker.rb
  config/initializers/open_uri.rb
Labels: ready to merge

#1133 Handle OpenURI::HTTPError 404 && avoid OpenURI StringIO creation
  app/workers/kyc/kycaid/address_worker.rb
  app/workers/kyc/kycaid/document_worker.rb
  config/initializers/open_uri.rb
Labels: ready to merge

#1136 Fix: Handle Document <-> Facial verification KYCAID
  app/workers/kyc/kycaid/verifications_worker.rb
Labels: ready to merge

#1134 Fix: Handle Document <-> Facial verification KYCAID
  app/workers/kyc/kycaid/verifications_worker.rb
Labels: ready to merge

#1138 Add security.md
  docs/security.md
Labels: need qa
