Repository openware/barong, pull requests merged in 2020-04, with the labels that each got.

#1048 Refactor: push cloudflare IPs list to rails trusted proxies
  config/application.rb
  config/initializers/trusted_proxies.rb
  lib/barong/cloudflare_middleware.rb
Labels: master, ready to merge

#1047 Refactor: push cloudflare IPs list to rails trusted proxies
  config/application.rb
  config/initializers/trusted_proxies.rb
  lib/barong/cloudflare_middleware.rb
Labels: ready to merge, v2.4

#1046 Refactor: push cloudflare IPs list to rails trusted proxies
  config/application.rb
  config/initializers/trusted_proxies.rb
  lib/barong/cloudflare_middleware.rb
Labels: 2.3, ready to merge

#1050 Feature: PUT resource/users/me data field
  app/api/v2/resource/users.rb
  spec/api/v2/resource/users_spec.rb
Labels: ready to merge

#1053 Feature: Add Sentry error tracking system
  Gemfile
  Gemfile.lock
  config/application.rb
  docs/configuration.md
Labels: peer:approved, ready to merge

#1049 Fix: Add docs && changelog generation on master branch
  .drone.yml
Labels: peer:approved, ready to merge

#1054 Enhancement: allow only latest requested token on reset_pass
  app/api/v2/identity/users.rb
  lib/barong/jwt.rb
  spec/api/v2/identity/users_spec.rb
Labels: PR: review needed

#1059 Refactor: fix typo in emails, remove inline attachment
  app/mailers/postmaster.rb
  app/views/postmaster/deposit_accepted.en.html.erb
  app/views/postmaster/email_confirmation.en.html.erb
  app/views/postmaster/email_confirmation.ru.html.erb
  app/views/postmaster/label.en.html.erb
  app/views/postmaster/new_beneficiary.en.html.erb
  app/views/postmaster/password_reset.en.html.erb
  app/views/postmaster/password_reset.ru.html.erb
  app/views/postmaster/session_create.en.html.erb
  app/views/postmaster/withdraw_succeed.en.html.erb
  spec/mailers/postmaster_spec.rb
Labels: PR: review needed

#1057 Feature: support TRUE_CLIENT_IP header as IP source
  app/api/v2/utils.rb
  config/initializers/barong.rb
  docs/configuration.md
  lib/barong/authorize.rb
  spec/api/v2/admin/users_spec.rb
  spec/api/v2/auth/auth_spec.rb
Labels: PR: review needed

#1058 Enhancement: remove api_key signature blacklisting
  lib/barong/authorize.rb
  spec/api/v2/auth/auth_spec.rb
Labels: PR: review needed
