Repository openware/barong, pull requests merged in 2020-03, with the labels that each got.

#1021 Enhancement: security updates
  app/api/v2/identity/sessions.rb
  app/api/v2/identity/users.rb
  app/api/v2/identity/utils.rb
  app/services/captcha_service.rb
  config/barong.yml
  docs/general/errors.md
  spec/api/v2/identity/sessions_spec.rb
  spec/api/v2/identity/users_spec.rb
Labels: ready to merge

#1031 Fix: get rid of wrong unicode symbol
  app/api/v2/identity/utils.rb
  config/barong.yml
  spec/api/v2/identity/sessions_spec.rb
  spec/api/v2/identity/users_spec.rb
Labels: ready to merge, type: bug

#1032 Enhancement: raise fatal error if cant connect to redis in production
  config/initializers/redis.rb
Labels: ready to merge

#1033 Enhancement: avoid errors on missing configurations
  app/api/v2/identity/utils.rb
  app/models/user.rb
  spec/api/v2/identity/users_spec.rb
  spec/models/user_spec.rb
Labels: ready to merge

#1035 Setup redeploy on devkube
  .drone.yml
Labels: ready to merge

#1030 Enhancement: rework api key nonce policy
  config/initializers/barong.rb
  docs/configuration.md
  docs/general/api-keys.md
  lib/barong/authorize.rb
  spec/api/v2/auth/auth_spec.rb
  spec/api/v2/auth/csrf_spec.rb
  spec/api/v2/auth/rbac_spec.rb
Labels: ready to merge

#1015 Feature: Add ability to support multiple profiles
  app/api/v2/admin/profiles.rb
  app/api/v2/admin/users.rb
  app/api/v2/entities/user_with_full_info.rb
  app/api/v2/entities/user_with_kyc.rb
  app/api/v2/entities/user_with_profile.rb
  app/api/v2/management/users.rb
  app/api/v2/queries/user_filter.rb
  app/api/v2/queries/user_with_label_filter.rb
  app/api/v2/resource/profiles.rb
  app/models/document.rb
  app/models/profile.rb
  app/models/user.rb
  db/migrate/20200318152130_add_default_state_to_profiles_table.rb
  db/schema.rb
  spec/api/v2/admin/profiles_spec.rb
  spec/api/v2/admin/users_spec.rb
  spec/api/v2/entities/user_with_full_spec.rb
  spec/api/v2/management/labels_spec.rb
  spec/api/v2/management/users_spec.rb
  spec/api/v2/resource/profiles_spec.rb
  spec/models/profile_spec.rb
  spec/models/user_spec.rb
Labels: PR: review needed, peer:approved, ready to merge

#959 Feature: Ability to send emails
  Gemfile
  Gemfile.lock
  app/mailers/application_mailer.rb
  app/mailers/postmaster.rb
  app/models/user.rb
  app/services/event_mailer.rb
  app/views/layouts/mailer.html.erb
  app/views/postmaster/deposit_accepted.en.html.erb
  app/views/postmaster/email_confirmation.en.html.erb
  app/views/postmaster/email_confirmation.ru.html.erb
  app/views/postmaster/label.en.html.erb
  app/views/postmaster/new_beneficiary.en.html.erb
  app/views/postmaster/new_email_template.en.html.erb
  app/views/postmaster/password_reset.en.html.erb
  app/views/postmaster/password_reset.ru.html.erb
  app/views/postmaster/session_create.en.html.erb
  app/views/postmaster/withdraw_succeed.en.html.erb
  bin/mailer
  config/backend.yml
  config/environments/production.rb
  config/initializers/barong.rb
  config/mailer.yml
  docs/configuration.md
  docs/mailer.md
  lib/tasks/.keep
  lib/tasks/mailer.rake
  public/logo.png
  spec/mailers/postmaster_spec.rb
  spec/mailers/previews/mailer_preview.rb
Labels: peer:approved, ready to merge

#1041 Feature/email template
  app/views/layouts/mailer.html.erb
  app/views/postmaster/deposit_accepted.en.html.erb
  app/views/postmaster/email_confirmation.en.html.erb
  app/views/postmaster/email_confirmation.ru.html.erb
  app/views/postmaster/label.en.html.erb
  app/views/postmaster/new_beneficiary.en.html.erb
  app/views/postmaster/new_email_template.en.html.erb
  app/views/postmaster/password_reset.en.html.erb
  app/views/postmaster/password_reset.ru.html.erb
  app/views/postmaster/session_create.en.html.erb
  app/views/postmaster/withdraw_succeed.en.html.erb
  public/logo.png
Labels: PR: do not merge

#1042 [Fix] Update rails to 5.2.4.2
  Gemfile.lock
  spec/models/activity_spec.rb
Labels: ready to merge
