Repository openware/barong, pull requests merged in 2020-10, with the labels that each got.

#1154 Fix vault initializer
  .drone.yml
  config/initializers/vault.rb
Labels: 2.6

#1150 Feature: Add encryption on profile, phone and document models
  app/api/v2/admin/profiles.rb
  app/api/v2/admin/users.rb
  app/api/v2/management/profiles.rb
  app/api/v2/queries/user_filter.rb
  app/api/v2/resource/documents.rb
  app/api/v2/resource/phones.rb
  app/helpers/salted_crc32.rb
  app/models/concerns/encryptable.rb
  app/models/document.rb
  app/models/phone.rb
  app/models/profile.rb
  app/services/encryption_service.rb
  app/services/mock_phone_verify_service.rb
  app/services/twilio_sms_send_service.rb
  config/initializers/barong.rb
  db/migrate/20200929143711_add_encrypted_values_to_phones_profiles_documents.rb
  db/migrate/20201001112814_change_document_fields_position.rb
  db/schema.rb
  docs/configuration.md
  docs/general/encryption.md
  scripts/benchmark/phones.rb
  scripts/benchmark/profiles.rb
  spec/api/v2/admin/profiles_spec.rb
  spec/api/v2/management/documents_spec.rb
  spec/api/v2/resource/addresses_spec.rb
  spec/api/v2/resource/documents_spec.rb
  spec/api/v2/resource/profiles_spec.rb
  spec/models/document_spec.rb
  spec/rails_helper.rb
  spec/services/encryption_service_spec.rb
Labels: 2.6, ready to merge

#1149 Fix: Mailer reinitialize on lost db connection instead of raise error
  app/services/event_mailer.rb
Labels: 2.6, PR: review needed, type: fix

#1152 Fix: Mailer reinitialize on lost db connection instead of raise error
  app/services/event_mailer.rb
Labels: 2.5, PR: review needed, type: fix

#1153 Fix: Mailer reinitialize on lost db connection instead of raise error
  app/services/event_mailer.rb
Labels: PR: review needed, type: fix, v2.4

#1156 Feature: Mask last_name, dob, doc_number, phone_number on API level
  app/api/v2/admin/activities.rb
  app/api/v2/admin/api_keys.rb
  app/api/v2/admin/entities/activity_with_user.rb
  app/api/v2/admin/entities/admin_activity.rb
  app/api/v2/admin/entities/document.rb
  app/api/v2/admin/entities/phone.rb
  app/api/v2/admin/entities/profile.rb
  app/api/v2/admin/entities/user_with_kyc.rb
  app/api/v2/admin/entities/user_with_profile.rb
  app/api/v2/admin/profiles.rb
  app/api/v2/admin/users.rb
  app/api/v2/entities/document.rb
  app/api/v2/entities/phone.rb
  app/api/v2/entities/profile.rb
  app/api/v2/management/exceptions/base.rb
  app/models/document.rb
  app/models/phone.rb
  app/models/profile.rb
  docs/general/encryption.md
  spec/api/v2/admin/activities_spec.rb
  spec/api/v2/admin/api_keys_spec.rb
  spec/api/v2/admin/profiles_spec.rb
  spec/api/v2/admin/users_spec.rb
  spec/api/v2/identity/sessions_spec.rb
  spec/api/v2/identity/users_spec.rb
  spec/api/v2/management/profiles_spec.rb
  spec/api/v2/resource/documents_spec.rb
  spec/api/v2/resource/phones_spec.rb
  spec/api/v2/resource/profiles_spec.rb
  spec/factories/user.rb
  spec/models/ability_spec.rb
  spec/models/activity_spec.rb
  spec/models/document_spec.rb
  spec/models/label_spec.rb
  spec/models/level_spec.rb
  spec/models/phone_spec.rb
  spec/models/profile_spec.rb
  spec/models/restrictions_spec.rb
  spec/models/user_spec.rb
Labels: 2.6, PR: review needed

#1157 Feature: Add key expiration time and rotation tasks
  app/services/encryption_service.rb
  docs/general/encryption.md
  lib/tasks/rotate.rake
  spec/services/encryption_service_spec.rb
Labels: 2.6, PR: review needed

#1158 Fix: Delete mask fields on management API
  app/api/v2/management/base.rb
  app/api/v2/management/documents.rb
  app/api/v2/management/entities/document.rb
  app/api/v2/management/entities/phone.rb
  app/api/v2/management/entities/profile.rb
  app/api/v2/management/entities/user_with_kyc.rb
  app/api/v2/management/entities/user_with_profile.rb
  app/api/v2/management/labels.rb
  app/api/v2/management/profiles.rb
  app/api/v2/management/users.rb
  spec/api/v2/management/labels_spec.rb
  spec/api/v2/management/profiles_spec.rb
  spec/api/v2/management/users_spec.rb
Labels: 2.6, PR: review needed

#1160 Fix: Skip validation on migration for encrypted fields
  db/migrate/20200929143711_add_encrypted_values_to_phones_profiles_documents.rb
Labels: 2.6, PR: review needed

#1161 Feature: Add management API for phone creation
  Gemfile
  Gemfile.lock
  app/api/v2/management/base.rb
  app/api/v2/management/phones.rb
  app/models/phone.rb
  docs/api/management.json
  docs/api/management.md
  spec/api/v2/admin/users_spec.rb
  spec/api/v2/management/phones_spec.rb
  spec/models/phone_spec.rb
Labels: 2.6, PR: review needed

#1162 Feature: Add read/delete phones for management API
  app/api/v2/management/base.rb
  app/api/v2/management/labels.rb
  app/api/v2/management/phones.rb
  docs/api/management.md
  spec/api/v2/management/phones_spec.rb
Labels: 2.6, PR: review needed

#1166 Fix: Add string length limit for encrypted fields
  app/models/profile.rb
  db/migrate/20200929143711_add_encrypted_values_to_phones_profiles_documents.rb
  db/schema.rb
  spec/models/profile_spec.rb
Labels: 2.6, PR: review needed

#1165 Fix: ApiKey creating only on account holder active state && Refactoring
  app/models/activity.rb
  app/models/api_key.rb
  app/models/comment.rb
  app/models/data_storage.rb
  app/models/document.rb
  app/models/label.rb
  app/models/level.rb
  app/models/permission.rb
  app/models/phone.rb
  app/models/service_account.rb
  app/models/user.rb
  spec/factories/api_keys.rb
  spec/factories/document.rb
  spec/factories/phones.rb
  spec/models/ability_spec.rb
  spec/models/api_key_spec.rb
  spec/models/document_spec.rb
  spec/models/profile_spec.rb
  spec/support/helper.rb
Labels: 2.6, PR: review needed
