Repository openware/barong, pull requests merged in 2020-07, with the labels that each got.

#1069 KYCAID integration
  .drone.yml
  Gemfile
  Gemfile.lock
  app/api/v2/base.rb
  app/api/v2/management/documents.rb
  app/api/v2/public/base.rb
  app/api/v2/public/general.rb
  app/api/v2/resource/addresses.rb
  app/api/v2/resource/base.rb
  app/api/v2/resource/documents.rb
  app/api/v2/resource/profiles.rb
  app/models/document.rb
  app/models/profile.rb
  app/services/kyc_service.rb
  app/workers/kyc/kycaid/address_worker.rb
  app/workers/kyc/kycaid/applicant_worker.rb
  app/workers/kyc/kycaid/document_worker.rb
  app/workers/kyc/kycaid/verifications_worker.rb
  config/authz_rules.yml
  config/barong.yml
  config/initializers/barong.rb
  db/migrate/20200514123908_add_identificator_to_documents_table.rb
  db/migrate/20200701115721_add_doc_category_to_documents.rb
  db/schema.rb
  spec/api/v2/management/documents_spec.rb
  spec/api/v2/public/general_spec.rb
  spec/api/v2/resource/addresses_spec.rb
  spec/api/v2/resource/documents_spec.rb
  spec/api/v2/resource/profiles_spec.rb
  spec/models/document_spec.rb
  spec/models/profile_spec.rb
  spec/models/user_spec.rb
  spec/workers/address_worker_spec.rb
  spec/workers/applicant_worker_spec.rb
  spec/workers/document_worker_spec.rb
  spec/workers/verification_worker_spec.rb
Labels: in progress, need qa, specs needed

#1113 Update Dockerfile
  Dockerfile
Labels: peer:approved, ready to merge

#1115 Feature: Add redis cluster support
  config/environments/production.rb
  config/initializers/barong.rb
  docs/configuration.md
Labels: peer:approved, ready to merge

#1108 Enhancement: Add ordering to admin users, api_keys and resources api_keys endpoint
  app/api/v2/admin/api_keys.rb
  app/api/v2/admin/users.rb
  app/api/v2/resource/api_keys.rb
  spec/api/v2/admin/api_keys_spec.rb
  spec/api/v2/admin/users_spec.rb
  spec/api/v2/resource/api_keys_spec.rb
Labels: peer:approved, ready to merge

#1095 Enhancement: Add ordering to admin users, api_keys and resources api_keys endpoint
  app/api/v2/admin/api_keys.rb
  app/api/v2/admin/users.rb
  app/api/v2/resource/api_keys.rb
  spec/api/v2/admin/api_keys_spec.rb
  spec/api/v2/admin/users_spec.rb
  spec/api/v2/resource/api_keys_spec.rb
Labels: master, peer:approved, ready to merge

#1120 Add ability for admin to create comments
  app/api/v2/admin/profiles.rb
  config/barong.yml
  config/initializers/barong.rb
  db/migrate/20200602075906_add_author_to_profiles.rb
  db/schema.rb
  docs/general/profiles.md
  spec/api/v2/admin/profiles_spec.rb
  spec/factories/profile.rb
Labels: ready to merge

#1121 Feature: Add ability for admin to create comments
  app/api/v2/admin/users.rb
  app/api/v2/entities/comment.rb
  app/api/v2/entities/user_with_kyc.rb
  app/models/comment.rb
  app/models/user.rb
  db/migrate/20200609144734_create_comments.rb
  db/schema.rb
  spec/api/v2/admin/users_spec.rb
  spec/api/v2/management/users_spec.rb
Labels: ready to merge

#1126 Fix: small changes in profile flow
  app/api/v2/resource/profiles.rb
  app/models/profile.rb
Labels: ready to merge
