Repository openware/barong, pull requests merged in 2020-01, with the labels that each got.

#991 [ci skip] API keys creation and usage doc
  README.md
  docs/general/api-keys.md
  docs/images/api-keys-1.jpeg
  docs/images/api-keys-2.jpeg
Labels: peer:approved, ready to merge

#993 [ci skip] Guardrails integration
  .guardrails/ignore
Labels: peer:approved, ready to merge

#994 Enhauncement: rework captcha policy
  app/api/v2/identity/utils.rb
  config/initializers/barong.rb
  config/initializers/captcha_policy.rb
  docs/general/captcha.md
  docs/general/errors.md
  lib/barong/app.rb
  lib/barong/captcha_policy.rb
  spec/api/v2/identity/sessions_spec.rb
  spec/api/v2/identity/users_spec.rb
  spec/models/user_spec.rb
Labels: ready to merge, type: enhancement

#1000 Fix: Support new MaxmindDB download policy
  .drone.yml
  Dockerfile
  docs/general/event_api.md
  spec/api/v2/management/documents_spec.rb
  spec/api/v2/resource/documents_spec.rb
  spec/models/user_spec.rb
Labels: ready to merge

#999 Fix: Support new MaxmindDB download policy
  .drone.yml
  Dockerfile
  docs/general/event_api.md
  spec/api/v2/management/documents_spec.rb
  spec/api/v2/resource/documents_spec.rb
Labels: ready to merge

#1001 Configuration unifying and documentation
  .drone.yml
  README.md
  VERSION
  app/api/v2/identity/users.rb
  app/api/v2/identity/utils.rb
  app/api/v2/resource/documents.rb
  app/api/v2/resource/phones.rb
  app/api/v2/resource/users.rb
  app/models/user.rb
  app/services/mock_phone_verify_service.rb
  app/services/totp_service.rb
  app/services/twilio_sms_send_service.rb
  app/services/twilio_verify_service.rb
  config.ru
  config/initializers/barong.rb
  config/initializers/barong_config.rb
  config/initializers/carrierwave.rb
  config/initializers/cors.rb
  config/initializers/document.rb
  config/initializers/document_types.rb
  config/initializers/geetest.rb
  config/initializers/phone.rb
  config/initializers/recaptcha.rb
  config/initializers/sessions_store.rb
  config/initializers/user_storage_titles.rb
  config/initializers/vault.rb
  docs/configuration.md
  lib/barong/app.rb
  lib/barong/authorize.rb
  lib/barong/event_api.rb
  lib/barong/geo_ip.rb
  lib/barong/seed.rb
  spec/api/v2/identity/sessions_spec.rb
  spec/api/v2/identity/users_spec.rb
  spec/api/v2/resource/phones_spec.rb
  spec/lib/barong/seed_spec.rb
  spec/models/user_spec.rb
Labels: PR: review needed, double check

#1004 Feature: GET /identity/configs - tiny configurations endpoint
  app/api/v2/identity/general.rb
  spec/api/v2/identity/general_spec.rb
Labels: PR: review needed, type: feature

#1002 Fix: changes in recaptcha verification behaviour
  app/api/v2/identity/utils.rb
  app/services/captcha_service.rb
Labels: PR: review needed, ready to merge

#986 Feature: introduce CSRF protection
  app/api/v2/entities/user_with_full_info.rb
  app/api/v2/identity/sessions.rb
  app/api/v2/identity/users.rb
  app/api/v2/identity/utils.rb
  config/initializers/barong.rb
  docs/configuration.md
  lib/barong/authorize.rb
  spec/api/v2/auth/audit_spec.rb
  spec/api/v2/auth/csrf_spec.rb
  spec/spec_helper.rb
Labels: PR: review needed

#1005 Feature: Make processes and threads configurable
  config/database.yml
  config/puma.rb
Labels: peer:approved, ready to merge

#1007 Fix: add missing redis_url in Barong::App.config
  config/initializers/barong.rb
Labels: ready to merge

#1008 Enhancement: improve log coverage, fix log_level config in prod env
  config/cable.yml
  config/environments/development.rb
  config/environments/production.rb
  lib/barong/activity_logger.rb
  lib/barong/authorize.rb
Labels: ready to merge
