Repository openware/barong, pull requests merged in 2020-12, with the labels that each got.

#1182 Feature: Add rake task for deleting activities && Add documentation
  docs/general/activities.md
  lib/tasks/activities.rake
Labels: 2.7, ready to merge

#1181 Feature: add the ability to update user email by superadmin
  app/api/v2/admin/users.rb
  docs/general/errors.md
  spec/api/v2/admin/users_spec.rb
Labels: PR: review needed

#1184 Feature: Update SDK version
  .drone.yml
Labels: 2.7, ready to merge

#1180 Fix: Delete redundant permissions
  app/services/event_mailer.rb
  config/seeds.yml
Labels: 2.5, ready to merge

#1178 Fix: Delete redundant permissions
  app/services/event_mailer.rb
  config/seeds.yml
Labels: 2.6, ready to merge

#1177 Fix: Delete redundant permissions
  app/services/event_mailer.rb
  config/seeds.yml
Labels: 2.7, ready to merge

#1197 Add permissions:load rake task
  lib/tasks/permissions.rake
Labels: 2.6

#1196 Add permissions:load rake task
  lib/tasks/permissions.rake
Labels: 2.7

#1198 Fix: Unify mailer language keys && Add backtrace
  app/services/event_mailer.rb
  lib/barong/activity_logger.rb
Labels: 2.6

#1199 Fix: Unify mailer language keys && Add backtrace
  app/services/event_mailer.rb
  lib/barong/activity_logger.rb
Labels: 2.7

#1200 Fix: Unify mailer language keys && Add backtrace
  app/services/event_mailer.rb
  lib/barong/activity_logger.rb
Labels: 2.5

#1171 Add CSRF token in API key documentation
  docs/general/api-keys.md
Labels: v2.4

#1170 Docs/2 5 apikeys
  docs/general/api-keys.md
Labels: 2.5

#1213 Feature: Blocklogin restrictions
  app/controllers/authorize_controller.rb
  app/models/restriction.rb
  docs/restrictions.md
  spec/api/v2/auth/restriction_spec.rb
  spec/models/restrictions_spec.rb
Labels: 2.7, PR: review needed

#1215 Fix: Restrictions specs
  spec/api/v2/auth/restriction_spec.rb
Labels: PR: review needed

#1214 Feature: Blocklogin restrictions (#1213)
  app/controllers/authorize_controller.rb
  app/models/restriction.rb
  docs/restrictions.md
  spec/api/v2/auth/restriction_spec.rb
  spec/models/restrictions_spec.rb
Labels: 2.6
