Repository openware/barong, pull requests merged in 2021-02, with the labels that each got.

#1245 Feature: Implement auth0
  .gitignore
  app/api/v2/identity/sessions.rb
  app/api/v2/public/general.rb
  app/models/user.rb
  config/initializers/barong.rb
  docs/configuration.md
  docs/general/auth0.md
  docs/images/auth0_dashboard.png
  docs/images/auth0_pkce.png
  docs/images/auth0_settings.png
  lib/barong/auth0/jwt.rb
  lib/barong/event_api.rb
  lib/barong/jwt.rb
  spec/api/v2/identity/sessions_spec.rb
  spec/models/user_spec.rb
Labels: 2.6, ready to merge

#1246 Feature: Add ability to register first user with superadmin role
  Gemfile
  Gemfile.lock
  app/api/v2/identity/users.rb
  config/initializers/barong.rb
  config/seeds.yml
  docs/configuration.md
  lib/barong/seed.rb
  spec/api/v2/identity/users_spec.rb
  spec/lib/barong/seed_spec.rb
  spec/spec_helper.rb
Labels: 2.6

#1239 Enhancement: Add Kaigara installation to the Dockerfile
  Dockerfile
Labels: type: enhancement

#1247 Feature: Add ability to update owner_uid
  app/api/v2/management/service_accounts.rb
  app/models/label.rb
  app/models/service_account.rb
  app/models/user.rb
  db/migrate/20210218135634_change_owner_id_requirement.rb
  db/schema.rb
  spec/api/v2/management/service_accounts_spec.rb
  spec/factories/service_account.rb
Labels: ready to merge

#1251 Feature: Add management API endpoints to create/update APIkeys
  app/api/v2/management/api_keys.rb
  app/api/v2/management/base.rb
  app/models/service_account.rb
  config/initializers/barong.rb
  docs/configuration.md
  spec/api/v2/management/api_keys_spec.rb
  spec/factories/service_account.rb
Labels: 2.6, ready to merge
