Repository openware/barong, pull requests merged in 2021-01, with the labels that each got.

#1202 Feature: Mailer improvements
  Gemfile
  Gemfile.lock
  app/services/event_mailer.rb
  bin/spring
  config/initializers/barong.rb
  config/initializers/event_api.rb
  docs/development/mailer.md
  docs/images/amqp-mailer-schema.jpg
  docs/images/mailer-retry.jpg
  docs/mailer.md
  lib/barong/event_api.rb
  lib/barong/keystore.rb
Labels: 2.7

#1209 Feature: Add health checks && delete unused files
  app/api/v2/public/general.rb
  app/services/health_checker.rb
  config/management_api_v1.yml
  config/templates/management_api_v1.yml.erb
  lib/assets/.keep
  test/application_system_test_case.rb
  test/controllers/.keep
  test/fixtures/.keep
  test/fixtures/files/.keep
  test/helpers/.keep
  test/integration/.keep
  test/mailers/.keep
  test/models/.keep
  test/system/.keep
  test/test_helper.rb
Labels: 2.7

#1218 Fix: Reject from retry when JWT:VerificationError raised
  app/services/event_mailer.rb
Labels: ready to merge

#1221 Fix: Record activity log after mysql connection lost
  lib/barong/activity_logger.rb
Labels: ready to merge

#1219 Fix: Prevent label duplication
  .gitignore
  app/services/kyc_service.rb
  db/migrate/20210113091207_add_unique_index_on_labels.rb
  db/schema.rb
  spec/services/kyc_service_spec.rb
Labels: ready to merge

#1228 Fix: Missing model annotation after migration (for 2-6-stable)
  lib/tasks/auto_annotate_models.rake
Labels: ready to merge

#1224 Add nickname into signup & users
  app/api/v2/entities/user.rb
  app/api/v2/entities/user_with_full_info.rb
  app/api/v2/entities/user_with_kyc.rb
  app/api/v2/entities/user_with_profile.rb
  app/api/v2/identity/users.rb
  app/models/user.rb
  db/migrate/20210119082215_add_username_to_users.rb
  db/schema.rb
  docs/api/barong_admin_api_v2.md
  docs/api/barong_management_api_v2.md
  docs/api/barong_user_api_v2.md
  spec/api/v2/admin/users_spec.rb
  spec/api/v2/identity/users_spec.rb
  spec/api/v2/management/users_spec.rb
  spec/models/user_spec.rb
Labels: PR: review needed

#1236 Feature: add ordering parameter to get labels endpoint
  app/api/v2/resource/labels.rb
  spec/api/v2/resource/labels_spec.rb
Labels: 2.6, ready to merge, type: feature
